sudo: required
language: bash
env:
  global:
    - BUILD_NAME=unity-example-travis
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_ce143bb546cb_key -iv $encrypted_ce143bb546cb_iv -in Unity_v2019.x.ulf.enc -out ./Unity_v2019.x.ulf -d
- export UNITY_LICENSE_CONTENT=`cat Unity_v2019.x.ulf`
- rm Unity_v2019.x.ulf  
- docker pull $IMAGE_NAME
jobs:
  include:
  - stage: build
    env: BUILD_TARGET=StandaloneLinux64 IMAGE_NAME=psorenson/unity2019image
    script:
      - "chmod +x ./ci/* && ./ci/docker_build.sh"
      - "sudo chmod -R 777 ./Builds/"
      - "cd ./Builds/"
      - "zip -r StandaloneLinux64.zip ./StandaloneLinux64/"
    deploy:
      provider: releases
      api_key: $GITHUB_API_KEY
      file: StandaloneLinux64.zip
      skip_cleanup: true
      on:
        tags: true
  - stage: build
    env: BUILD_TARGET=StandaloneOSX IMAGE_NAME=gableroux/unity3d:2019.3.7f1-mac
    script:
      - "chmod +x ./ci/* && ./ci/docker_build.sh"
      - "sudo chmod -R 777 ./Builds/"
      - "cd ./Builds/"
      - "zip -r StandaloneOSX.zip ./StandaloneOSX/"
    deploy:
      provider: releases
      api_key: $GITHUB_API_KEY
      file: StandaloneOSX.zip
      skip_cleanup: true
      on:
        tags: true