sudo: required
language: bash
env:
  global:
  - BUILD_NAME=ExampleProjectName
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_ce143bb546cb_key -iv $encrypted_ce143bb546cb_iv
  -in Unity_v2019.x.ulf.enc -out ./Unity_v2019.x.ulf -d
- openssl aes-256-cbc -K $encrypted_82766e747237_key -iv $encrypted_82766e747237_iv
  -in ./unity3d.alf -out ./Unity_v2019.x.ulf -d
- export UNITY_LICENSE_CONTENT=`cat Unity_v2019.x.ulf`
- rm Unity_v2019.x.ulf
- docker pull $IMAGE_NAME
jobs:
  include:
  - stage: test
    script: chmod +x ./ci/docker_test.sh && ./ci/docker_test.sh
    env: TEST_PLATFORM=editmode IMAGE_NAME=gableroux/unity3d:2019.3.0f6
    addons:
      artifacts:
        s3_region: us-west-1
        paths:
        - "$(pwd)/$TEST_PLATFORM-results.xml"
  - stage: test
    script: chmod +x ./ci/docker_test.sh && ./ci/docker_test.sh
    env: TEST_PLATFORM=playmode IMAGE_NAME=gableroux/unity3d:2019.3.0f6
    addons:
      artifacts:
        s3_region: us-west-1
        paths:
        - "$(pwd)/$TEST_PLATFORM-results.xml"
  - stage: build
    env: BUILD_TARGET=StandaloneLinux64 IMAGE_NAME=gableroux/unity3d:2019.3.0f6
    script: chmod +x ./ci/docker_build.sh && ./ci/docker_build.sh
    addons:
      artifacts:
        s3_region: us-west-1
        paths:
        - "./Builds/"
  - stage: build
    env: BUILD_TARGET=StandaloneOSX IMAGE_NAME=gableroux/unity3d:2019.3.0f6-mac
    script: chmod +x ./ci/docker_build.sh && ./ci/docker_build.sh
    addons:
      artifacts:
        s3_region: us-west-1
        paths:
        - "./Builds/"
